### ISSUE TITLE
[epic] Address confusion in definition of cohort in portal vs exported cohort

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#973]
As discussed and discovered today, the content of the right panel in the portal is not showing what is being exported in cohorts.

In the portal, the results show everything for all cases that contain the content that meets the search criteria (i.e., when user selects modality SM, all studies for the case that contains a study with SM will show up on the right).

In the exported cohort, only studies that contain SM will be included.

Effectively, portal operates with the selection at case level, and cohorts are defined applying the filter at the study level.

I propose we address this confusion by 

1) allowing the user to choose at what level the filter should be applied: case or study
2) make sure that the choice of the user re at what level the filter is applied is consistent between what is shown in the portal and what is exported into the manifest

The level at which the filter is applied should be stored as an attribute of the cohort (ie cohort granularity).

Re 1 above, it is noted that we do not have the index at the case level. Therefore, we can approach this in the following steps:

- [ ] initially make sure that what is shown in the portal is consistent with the exported manifest - filter is applied at the study level (will be addressed as part of this ticket)
- [ ] add granularity concept to the cohort (will be a lot of UI work) and include support for cohorts defined at the series level (ticket to be created)
- [ ] add the concept of case to the selection capability (ticket to be created)

<img width="846" alt="image" src="https://user-images.githubusercontent.com/313942/170553753-a12f68f5-98e3-4bcd-8af4-0f4473e2d2fb.png">

query just in case
```sql
with my_stuff as (SELECT manifest.StudyInstanceUID, string_agg(distinct(Modality), ",") as modalities
 FROM `canceridc-user-data.user_manifests.manifest_cohort_617_20220526_181455` as manifest
 join `bigquery-public-data.idc_current.dicom_all` as dicom_all
 on manifest.SOPInstanceUID = dicom_all.SOPInstanceUID
 group by manifest.StudyInstanceUID)
 select distinct(modalities) from my_stuff
```
